/*
    
    Esse é um exemplo disponibilizado no eBook AdvPL e TLPP 
    Esse eBook, está disponível no seguinte link: https://www.amazon.com.br/dp/B0F32JV54N 
    
*/


//Bibliotecas
#Include "tlpp-core.th"

//Declaração da namespace
Namespace custom.book

/*/{Protheus.doc} User Function tryCatch
Aciona tratativa e erro nos códigos
@type Function
@author Atilio
@since 12/03/2024
@see https://tdn.totvs.com/display/tec/Try...Catch
@example custom.book.u_tryCatch()
/*/

User Function tryCatch()
    Local aArea    := FWGetArea() As Array
    Private oError := Nil         As Object

    //Tenta executar os comandos
    TRY

        //Se a pergunta for confirmada, irá forçar passar pelo ErrorClass
        If FWAlertYesNo("Deseja forçar o erro e a saída do Try?", "Continua?")
            forceError()
        EndIf
        
        //Mostra mensagem
        FWAlertSuccess("Sucesso na execução do Try", "Teste Try ... Catch")

    //Caso houve falha, captura e exibe
    CATCH oError
        FWAlertError("Erro gerado: " + oError:Description , "Teste Try ... Catch")
    ENDTRY
  
    FWRestArea(aArea)
Return

Static Function forceError()
    oError := ErrorClass():New()
    oError:genCode := 19584
    oError:description := "Erro forçado dentro da função forceError()"
    THROW oError
Return
